version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
      
    working_directory: /go/src/github.com/gautema/goping
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go build .